bases:
  - ../cr-base-noenv/

patchesJson6902:
  - target:
      group: mytype
      version: v1alpha1
      kind: MyType
      name: test-cr
    path: ./patch.yaml
 
  # JSON patch cannot add to the env if it does not exist.
  # Patch needs to define creation of missing block