apiVersion: mytype/v1alpha1
kind: MyType
metadata:
  name: test-cr
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: djones6/test
        ports:
          - containerPort: 8080
