apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  template:
    spec:
      containers:
      - name: test
        env:
          - name: PEAR
            value: patch2
          - name: PLUM
            valueFrom:
              configMapKeyRef:
                name: patch2
                key: plumkey