apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2-deployment
spec:
  template:
    spec:
      containers:
      - name: test2
        env:
          - name: APPLE
            value: sweet
          - name: BANANA
            value: yellow